### ISSUE TITLE
What is the dataset format?

### ISSUE THREAD

**Issue by netsalesbg-ltd** [tryonlabs/tryondiffusion#57]
I am looking into training the model. But I cannot understand the format of the dataset.

https://github.com/tryonlabs/tryondiffusion/blob/d471b9175439ba555bdbeb16aa03213313c351db/tryondiffusion/trainer.py#L10-L20

Can you tell me what the different abbreveated folders stand for? The folders: `ip`, `jp`, `ia`, `ic` and `jg`. Can probably get `image-parse` from `ip` but the rest are a mistery.

**Comment by tanayag** [comment]
You can refer to the original paper, they have made notations like this.
